version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  angular: # name of the first service
    build: frontend # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding

  express: #name of the second service
    build: backend # specify the directory of the Dockerfile
    links:
      - mongodb
    ports:
      - "9000:9000" #specify ports forewarding
    environment:
      - MONGO_URI=mongodb://mongodb/zappy